### ISSUE TITLE
[수정] one to many 관계에 대한 join fetch 추가, LectureImage isActive == true 조건 추가

### ISSUE THREAD

**Issue by Park-Young-Hun** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#102]
## 수정 내용
- one to many 관계에 대한 join fetch 추가
- LectureImage isActive==true 조건 추가
- Tag isActive===true 조건 추가
- Lecture isActive==true 조건 추가

## 할 일
- [ ] one to many 관계에 대한 join fetch 추가
- [ ] LectureImage isActive == true 조건 추가
- [ ] Tag isActive===true 조건 추가
- [ ] Lecture isActive==true 조건 추가
- [ ] 테스트 작성

**Comment by NaLDo627** [comment]
@Park-Young-Hun 해당 이슈 언제쯤 완료될까요?

**Comment by Park-Young-Hun** [comment]
지금 확인했습니다, 죄송합니다! 7월 12일 화요일까지 완료해보겠습니다!

**Comment by NaLDo627** [comment]
@Park-Young-Hun 7월 16일인데요...피드백 부탁드립니다

**Comment by Park-Young-Hun** [comment]
막힌부분이 잘 안풀려 지연되었습니다.. 오늘까지 한 부분 Draft PR로 올려놓고 계속 해보겠습니다..!

**Comment by NaLDo627** [comment]
@Park-Young-Hun 이거 작업중이실까요?

**Comment by Park-Young-Hun** [comment]
@NaLDo627 넵 그래야할 것 같습니다.. 다른 이슈부터 작업 진행하겠습니다.
