### ISSUE TITLE
[기능] 매칭중인 Lecture List 삭제 기능

### ISSUE THREAD

**Issue by Park-Young-Hun** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#160]
## 기능 
- 매칭중인 Lecture List 삭제 기능

## 할 일
- [ ] 매칭중인 Lecture List 삭제 기능
- [ ] 테스트코드 작성

**Comment by NaLDo627** [comment]
- 현재 QA로만 해도 빠듯하고 심사를 일주일 안에 넘겨야 해서 새로운 기능 추가에 부담
- 클래스 일정 만료, 일정 삭제하면 disabled 처리 되므로 현재 이 기능으로 대체 가능
이런 이유로 디자인, 기능은 설계했으나 백로그 처리

위 이유로 해당 기능은 보류처리 합니다.
