### ISSUE TITLE
[업무] API 작업 목록 이슈화

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#22]
- 와이어 프레임을 토대로 필요한 API 목록을 산출, 이슈화 한다.

**Comment by NaLDo627** [comment]
@Park-Young-Hun 이슈 목록화 하시느라 고생 많으셨습니다!
추가로, 각 이슈에 기능별로 Milestone 붙여주시고, 이 이슈는 Close 처리 해주세요!

**Comment by Park-Young-Hun** [comment]
@NaLDo627 Milestone 붙였는데 헷갈렸던 부분이 좀 있어서 피드백 주시면 감사하겠습니다!

**Comment by NaLDo627** [comment]
@Park-Young-Hun 넵 괜찮은것 같습니다~!
