### ISSUE TITLE
[설계] ERD 수정사항 반영

### ISSUE THREAD

**Issue by Park-Young-Hun** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#24]
1. 카카오톡 ID가 어느 테이블에 종속 될 것 인지 기획 논의
2. 태그 테이블 삭제
3. 카테고리 parent_id 삭제

**Comment by NaLDo627** [comment]
1. coach 테이블에 종속됨
2. 삭제 완료
3. 삭제 완료

**Comment by NaLDo627** [comment]
2번에 태그는 사용한다고 합니다. 삭제 롤백
