### ISSUE TITLE
[기능] 클래스 상세 조회

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#26]
- 특정 클래스 내용을 상세히 조회할 수 있다.

**Comment by Park-Young-Hun** [comment]
클래스 상세 - 유저 입장 화면에 대한 논의가 필요할 듯 합니다.

**Comment by NaLDo627** [comment]
상세 조회시 클래스 info 및 클래스 (일정)을 같이 뿌려줄 수 있어야 함
