### ISSUE TITLE
[기능] 등록된 클래스 목록 조회

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#27]
## 기능 
- 등록된 클래스 목록 조회 기능

## 할 일
- [x] 등록된 클래스 목록 조회
- [x] 카테고리 별 등록된 클래스 목록 조회

## 마감기한 (선택)

**Comment by Park-Young-Hun** [comment]
카테고리 별 등록된 클래스 목록 조회 기능도 언급되면 좋을 것 같습니다!

**Comment by useonglee** [comment]
해당 API 더미데이터 먼저 부탁드려도 괜찮을까요!? 
더미데이터로 UI 작업 끝내놓으려고 합니다!

**Comment by NaLDo627** [comment]
@Park-Young-Hun 님, 해당 작업건 진행 중이시죠?
완료 끝나면 우성님께 노티 부탁드립니다.
