### ISSUE TITLE
[수정] user 테이블에 웹사이트 컬럼 추가

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#37]
## 수정 내용
- 기획상으로, 사용자 프로필에 웹사이트를 선택적으로 입력 가능하기 때문에, 해당 컬럼 추가가 필요하다.

## 할 일
- [x] [ERD](https://www.erdcloud.com/d/upxjamqGs5qPfYyXC) 상으로 웹사이트 컬럼 추가
- [x] liquibase 스키마 업데이트
- [x] Entity 업데이트
- [x] dbunit 테스트셋 업데이트

**Comment by Park-Young-Hun** [comment]
ERD에 portfolio 라는 컬럼으로 추가했습니다! website라는 키워드를 사용하지 않은 이유는 추후에 포트폴리오를 파일로 받을 경우엔 S3 URL이 들어갈 수 도 있다고 생각했기 때문입니다.
