### ISSUE TITLE
[기능] 로그아웃 기능

### ISSUE THREAD

**Issue by Park-Young-Hun** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#62]
## 기능 
- 로그아웃 기능

## 할 일
- [ ] 로그아웃 기능
- [ ] 테스트 코드 작성

**Comment by NaLDo627** [comment]
로그아웃은 단순히 클라이언트에서 JWT를 삭제하면 되는게 아닌가? 싶음
만약 추가 조치가 필요하다면 다시 open
