### ISSUE TITLE
[문의] 코치 등록 타이밍?

### ISSUE THREAD

**Issue by NaLDo627** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#84]
@Park-Young-Hun 

## 문의사항
- 코치 테이블에 데이터는 아래 중 언제 등록되는 걸까요?
    - 신규 회원가입 / 온보딩 때
    - 운영 클래스를 등록할 때
    - 운영 클래스를 마쳤을 때
    - 그 외

**Comment by NaLDo627** [comment]
효선님 답변입니다.

> 코치 등록 = 클래스 등록인데 하단바 클래스 등록으로 가능합니다! 더불어 클래스 등록이 하나도 안된 유저의 경우 운영 클래스 첫 화면에서 클래스 등록으로 연결되는 플로우가 있습니다.

**Comment by Park-Young-Hun** [comment]
클래스 등록하는 시점에 코치로서 등록되는 것이군요! 이해했습니다!

**Comment by NaLDo627** [comment]
## 문의 내용
사용자 자기소개 = 코치 자기소개 일까요?
만약 다르다면, 코치로 등록하게 되면 코치가 자기소개를 등록하는 화면이 따로 필요하지 않을까 싶어서요

> 사용자 자기소개가 플레이어, 코치 소개에도 동일하게 적용됩니다
코치 프로필을 따로 운영 클래스, 후기 개수를 보여줘서 플레이어 버전과의 차이점을 줬습니다.
원래는 코치 프로필 작성-노출을 따로해야 베스트인데 화면을 줄이는 과정에서 프로필 작성, 노출 부분을 합쳤습니다. 지금과 같은 프로필 형식으로 필요한 정보를 대체하고 클래스 소개도 따로 작성하게 되어 있어서 기능적으로 충분한 기능을 제공할 수 있을거라 예상합니다!
