### ISSUE TITLE
[업무] CORS 정책처리 방안 논의

### ISSUE THREAD

**Issue by Park-Young-Hun** [YAPP-Github/20th-ALL-Rounder-Team-2-BE#97]
## 요청 사항
- CORS 정책처리 방안 논의

## 할 일
- [ ] CORS 정책처리 방안 논의

**Comment by NaLDo627** [comment]
https://velog.io/@change/Spring-Boot-CORS%EC%99%80-Preflight%EC%97%90-%EA%B4%80%ED%95%9C-%EC%9D%B4%EC%8A%88

위 게시글에서 @CrossOrigin 을 사용하는 방식과 WebConfig 를 사용하는 방식이 있는데, 후자가 더 좋아보입니다~!

**Comment by Park-Young-Hun** [comment]
넵 알겠습니다! 그럼 해당 부분 만들어서 우선적으로 PR올리도록 하겠습니다!
그럼 혹시 allowedOrigins에는 어떤 도메인들까지 허용해야 된다고 생각하시나요?
일단 loaclhost:3000은 포함되어야 될 것 같습니다!

**Comment by NaLDo627** [comment]
@Park-Young-Hun 
개발 단계라 전체 허용(*) 해도 무관할 것 같습니다.
이후 운영 환경에서 해당 설정은 웹뷰 도메인에서만 허용되야 할 듯 합니다!

**Comment by Park-Young-Hun** [comment]
넵 알겠습니다! 답변 감사합니다!
